// Auto generated File
// DON'T EDIT BY HAND

import 'package:phosphoricons_flutter/phosphoricons_flutter.dart';

abstract class AllIcons {
  static List<PhosphorIconData> get icons => allFlatIconsAsMap.values.toList();

  static List<String> get names => allFlatIconsAsMap.keys.toList();

  static Map<String, PhosphorIconData> get allFlatIconsAsMap => {
    ...regularIcons,
    ...boldIcons,
    ...fillIcons,
  };

  static Map<String, PhosphorIconData> get regularIcons => {
    // ─── Finance & Money ───
    'bank': PhosphorIconsRegular.bank,
    'barcode': PhosphorIconsRegular.barcode,
    'calculator': PhosphorIconsRegular.calculator,
    'cash-register': PhosphorIconsRegular.cashRegister,
    'coin': PhosphorIconsRegular.coin,
    'coin-vertical': PhosphorIconsRegular.coinVertical,
    'coins': PhosphorIconsRegular.coins,
    'contactless-payment': PhosphorIconsRegular.contactlessPayment,
    'credit-card': PhosphorIconsRegular.creditCard,
    'currency-btc': PhosphorIconsRegular.currencyBtc,
    'currency-circle-dollar': PhosphorIconsRegular.currencyCircleDollar,
    'currency-dollar': PhosphorIconsRegular.currencyDollar,
    'currency-dollar-simple': PhosphorIconsRegular.currencyDollarSimple,
    'currency-eur': PhosphorIconsRegular.currencyEur,
    'currency-gbp': PhosphorIconsRegular.currencyGbp,
    'currency-inr': PhosphorIconsRegular.currencyInr,
    'currency-jpy': PhosphorIconsRegular.currencyJpy,
    'hand-coins': PhosphorIconsRegular.handCoins,
    'hand-deposit': PhosphorIconsRegular.handDeposit,
    'hand-withdraw': PhosphorIconsRegular.handWithdraw,
    'invoice': PhosphorIconsRegular.invoice,
    'money': PhosphorIconsRegular.money,
    'money-wavy': PhosphorIconsRegular.moneyWavy,
    'percent': PhosphorIconsRegular.percent,
    'piggy-bank': PhosphorIconsRegular.piggyBank,
    'poker-chip': PhosphorIconsRegular.pokerChip,
    'qr-code': PhosphorIconsRegular.qrCode,
    'receipt': PhosphorIconsRegular.receipt,
    'receipt-x': PhosphorIconsRegular.receiptX,
    'shopping-bag': PhosphorIconsRegular.shoppingBag,
    'shopping-bag-open': PhosphorIconsRegular.shoppingBagOpen,
    'shopping-cart': PhosphorIconsRegular.shoppingCart,
    'shopping-cart-simple': PhosphorIconsRegular.shoppingCartSimple,
    'storefront': PhosphorIconsRegular.storefront,
    'tip-jar': PhosphorIconsRegular.tipJar,
    'treasure-chest': PhosphorIconsRegular.treasureChest,
    'trolley': PhosphorIconsRegular.trolley,
    'vault': PhosphorIconsRegular.vault,
    'wallet': PhosphorIconsRegular.wallet,

    // ─── Charts & Statistics ───
    'chart-bar': PhosphorIconsRegular.chartBar,
    'chart-bar-horizontal': PhosphorIconsRegular.chartBarHorizontal,
    'chart-donut': PhosphorIconsRegular.chartDonut,
    'chart-line': PhosphorIconsRegular.chartLine,
    'chart-line-down': PhosphorIconsRegular.chartLineDown,
    'chart-line-up': PhosphorIconsRegular.chartLineUp,
    'chart-pie': PhosphorIconsRegular.chartPie,
    'chart-pie-slice': PhosphorIconsRegular.chartPieSlice,
    'chart-polar': PhosphorIconsRegular.chartPolar,
    'chart-scatter': PhosphorIconsRegular.chartScatter,
    'graph': PhosphorIconsRegular.graph,
    'presentation-chart': PhosphorIconsRegular.presentationChart,
    'projector-screen-chart': PhosphorIconsRegular.projectorScreenChart,
    'ranking': PhosphorIconsRegular.ranking,
    'trend-down': PhosphorIconsRegular.trendDown,
    'trend-up': PhosphorIconsRegular.trendUp,

    // ─── Navigation & Arrows (essential) ───
    'arrow-arc-left': PhosphorIconsRegular.arrowArcLeft,
    'arrow-arc-right': PhosphorIconsRegular.arrowArcRight,
    'arrow-circle-down': PhosphorIconsRegular.arrowCircleDown,
    'arrow-circle-left': PhosphorIconsRegular.arrowCircleLeft,
    'arrow-circle-right': PhosphorIconsRegular.arrowCircleRight,
    'arrow-circle-up': PhosphorIconsRegular.arrowCircleUp,
    'arrow-clockwise': PhosphorIconsRegular.arrowClockwise,
    'arrow-counter-clockwise': PhosphorIconsRegular.arrowCounterClockwise,
    'arrow-down': PhosphorIconsRegular.arrowDown,
    'arrow-left': PhosphorIconsRegular.arrowLeft,
    'arrow-right': PhosphorIconsRegular.arrowRight,
    'arrow-up': PhosphorIconsRegular.arrowUp,
    'arrows-clockwise': PhosphorIconsRegular.arrowsClockwise,
    'arrows-counter-clockwise': PhosphorIconsRegular.arrowsCounterClockwise,
    'arrows-down-up': PhosphorIconsRegular.arrowsDownUp,
    'arrows-horizontal': PhosphorIconsRegular.arrowsHorizontal,
    'arrows-left-right': PhosphorIconsRegular.arrowsLeftRight,
    'arrows-merge': PhosphorIconsRegular.arrowsMerge,
    'arrows-split': PhosphorIconsRegular.arrowsSplit,
    'arrows-vertical': PhosphorIconsRegular.arrowsVertical,
    'caret-circle-down': PhosphorIconsRegular.caretCircleDown,
    'caret-circle-left': PhosphorIconsRegular.caretCircleLeft,
    'caret-circle-right': PhosphorIconsRegular.caretCircleRight,
    'caret-circle-up': PhosphorIconsRegular.caretCircleUp,
    'caret-circle-up-down': PhosphorIconsRegular.caretCircleUpDown,
    'caret-down': PhosphorIconsRegular.caretDown,
    'caret-left': PhosphorIconsRegular.caretLeft,
    'caret-right': PhosphorIconsRegular.caretRight,
    'caret-up': PhosphorIconsRegular.caretUp,
    'caret-up-down': PhosphorIconsRegular.caretUpDown,
    'sign-in': PhosphorIconsRegular.signIn,
    'sign-out': PhosphorIconsRegular.signOut,
    'swap': PhosphorIconsRegular.swap,

    // ─── Actions (common UI) ───
    'check': PhosphorIconsRegular.check,
    'check-circle': PhosphorIconsRegular.checkCircle,
    'check-fat': PhosphorIconsRegular.checkFat,
    'check-square': PhosphorIconsRegular.checkSquare,
    'check-square-offset': PhosphorIconsRegular.checkSquareOffset,
    'checks': PhosphorIconsRegular.checks,
    'clipboard': PhosphorIconsRegular.clipboard,
    'clipboard-text': PhosphorIconsRegular.clipboardText,
    'copy': PhosphorIconsRegular.copy,
    'copy-simple': PhosphorIconsRegular.copySimple,
    'download': PhosphorIconsRegular.download,
    'download-simple': PhosphorIconsRegular.downloadSimple,
    'export': PhosphorIconsRegular.export,
    'eye': PhosphorIconsRegular.eye,
    'eye-closed': PhosphorIconsRegular.eyeClosed,
    'eye-slash': PhosphorIconsRegular.eyeSlash,
    'file-arrow-down': PhosphorIconsRegular.fileArrowDown,
    'file-arrow-up': PhosphorIconsRegular.fileArrowUp,
    'funnel': PhosphorIconsRegular.funnel,
    'funnel-simple': PhosphorIconsRegular.funnelSimple,
    'funnel-simple-x': PhosphorIconsRegular.funnelSimpleX,
    'funnel-x': PhosphorIconsRegular.funnelX,
    'link': PhosphorIconsRegular.link,
    'link-break': PhosphorIconsRegular.linkBreak,
    'link-simple': PhosphorIconsRegular.linkSimple,
    'link-simple-break': PhosphorIconsRegular.linkSimpleBreak,
    'magnifying-glass': PhosphorIconsRegular.magnifyingGlass,
    'magnifying-glass-minus': PhosphorIconsRegular.magnifyingGlassMinus,
    'magnifying-glass-plus': PhosphorIconsRegular.magnifyingGlassPlus,
    'minus': PhosphorIconsRegular.minus,
    'minus-circle': PhosphorIconsRegular.minusCircle,
    'minus-square': PhosphorIconsRegular.minusSquare,
    'pencil': PhosphorIconsRegular.pencil,
    'pencil-circle': PhosphorIconsRegular.pencilCircle,
    'pencil-line': PhosphorIconsRegular.pencilLine,
    'pencil-simple': PhosphorIconsRegular.pencilSimple,
    'plus': PhosphorIconsRegular.plus,
    'plus-circle': PhosphorIconsRegular.plusCircle,
    'plus-minus': PhosphorIconsRegular.plusMinus,
    'plus-square': PhosphorIconsRegular.plusSquare,
    'share': PhosphorIconsRegular.share,
    'share-fat': PhosphorIconsRegular.shareFat,
    'share-network': PhosphorIconsRegular.shareNetwork,
    'sort-ascending': PhosphorIconsRegular.sortAscending,
    'sort-descending': PhosphorIconsRegular.sortDescending,
    'trash': PhosphorIconsRegular.trash,
    'trash-simple': PhosphorIconsRegular.trashSimple,
    'upload': PhosphorIconsRegular.upload,
    'upload-simple': PhosphorIconsRegular.uploadSimple,
    'x': PhosphorIconsRegular.x,
    'x-circle': PhosphorIconsRegular.xCircle,
    'x-square': PhosphorIconsRegular.xSquare,

    // ─── Security & Authentication ───
    'fingerprint': PhosphorIconsRegular.fingerprint,
    'fingerprint-simple': PhosphorIconsRegular.fingerprintSimple,
    'key': PhosphorIconsRegular.key,
    'lock': PhosphorIconsRegular.lock,
    'lock-key': PhosphorIconsRegular.lockKey,
    'lock-key-open': PhosphorIconsRegular.lockKeyOpen,
    'lock-open': PhosphorIconsRegular.lockOpen,
    'lock-simple': PhosphorIconsRegular.lockSimple,
    'lock-simple-open': PhosphorIconsRegular.lockSimpleOpen,
    'scan': PhosphorIconsRegular.scan,
    'shield': PhosphorIconsRegular.shield,
    'shield-check': PhosphorIconsRegular.shieldCheck,
    'shield-star': PhosphorIconsRegular.shieldStar,
    'shield-warning': PhosphorIconsRegular.shieldWarning,

    // ─── Settings & Profile ───
    'gear': PhosphorIconsRegular.gear,
    'gear-fine': PhosphorIconsRegular.gearFine,
    'gear-six': PhosphorIconsRegular.gearSix,
    'identification-badge': PhosphorIconsRegular.identificationBadge,
    'identification-card': PhosphorIconsRegular.identificationCard,
    'palette': PhosphorIconsRegular.palette,
    'sliders': PhosphorIconsRegular.sliders,
    'sliders-horizontal': PhosphorIconsRegular.slidersHorizontal,
    'translate': PhosphorIconsRegular.translate,
    'user': PhosphorIconsRegular.user,
    'user-check': PhosphorIconsRegular.userCheck,
    'user-circle': PhosphorIconsRegular.userCircle,
    'user-circle-gear': PhosphorIconsRegular.userCircleGear,
    'user-focus': PhosphorIconsRegular.userFocus,
    'user-gear': PhosphorIconsRegular.userGear,
    'user-list': PhosphorIconsRegular.userList,
    'user-minus': PhosphorIconsRegular.userMinus,
    'user-plus': PhosphorIconsRegular.userPlus,
    'user-switch': PhosphorIconsRegular.userSwitch,
    'users': PhosphorIconsRegular.users,
    'users-three': PhosphorIconsRegular.usersThree,
    'users-four': PhosphorIconsRegular.usersFour,

    // ─── Notifications & Communication ───
    'bell': PhosphorIconsRegular.bell,
    'bell-ringing': PhosphorIconsRegular.bellRinging,
    'bell-simple': PhosphorIconsRegular.bellSimple,
    'bell-simple-ringing': PhosphorIconsRegular.bellSimpleRinging,
    'bell-simple-slash': PhosphorIconsRegular.bellSimpleSlash,
    'bell-slash': PhosphorIconsRegular.bellSlash,
    'envelope': PhosphorIconsRegular.envelope,
    'envelope-simple': PhosphorIconsRegular.envelopeSimple,
    'notification': PhosphorIconsRegular.notification,

    // ─── Date & Time ───
    'calendar': PhosphorIconsRegular.calendar,
    'calendar-blank': PhosphorIconsRegular.calendarBlank,
    'calendar-check': PhosphorIconsRegular.calendarCheck,
    'calendar-dot': PhosphorIconsRegular.calendarDot,
    'calendar-dots': PhosphorIconsRegular.calendarDots,
    'calendar-heart': PhosphorIconsRegular.calendarHeart,
    'calendar-minus': PhosphorIconsRegular.calendarMinus,
    'calendar-plus': PhosphorIconsRegular.calendarPlus,
    'calendar-x': PhosphorIconsRegular.calendarX,
    'clock': PhosphorIconsRegular.clock,
    'clock-afternoon': PhosphorIconsRegular.clockAfternoon,
    'clock-clockwise': PhosphorIconsRegular.clockClockwise,
    'clock-counter-clockwise': PhosphorIconsRegular.clockCounterClockwise,
    'hourglass': PhosphorIconsRegular.hourglass,
    'hourglass-high': PhosphorIconsRegular.hourglassHigh,
    'hourglass-low': PhosphorIconsRegular.hourglassLow,
    'hourglass-medium': PhosphorIconsRegular.hourglassMedium,
    'hourglass-simple': PhosphorIconsRegular.hourglassSimple,
    'timer': PhosphorIconsRegular.timer,

    // ─── UI & Layout ───
    'bookmark': PhosphorIconsRegular.bookmark,
    'bookmark-simple': PhosphorIconsRegular.bookmarkSimple,
    'bookmarks': PhosphorIconsRegular.bookmarks,
    'bookmarks-simple': PhosphorIconsRegular.bookmarksSimple,
    'circle': PhosphorIconsRegular.circle,
    'circle-dashed': PhosphorIconsRegular.circleDashed,
    'circle-half': PhosphorIconsRegular.circleHalf,
    'columns': PhosphorIconsRegular.columns,
    'crown': PhosphorIconsRegular.crown,
    'crown-simple': PhosphorIconsRegular.crownSimple,
    'diamond': PhosphorIconsRegular.diamond,
    'dots-nine': PhosphorIconsRegular.dotsNine,
    'dots-six': PhosphorIconsRegular.dotsSix,
    'dots-six-vertical': PhosphorIconsRegular.dotsSixVertical,
    'dots-three': PhosphorIconsRegular.dotsThree,
    'dots-three-circle': PhosphorIconsRegular.dotsThreeCircle,
    'dots-three-circle-vertical': PhosphorIconsRegular.dotsThreeCircleVertical,
    'dots-three-outline': PhosphorIconsRegular.dotsThreeOutline,
    'dots-three-outline-vertical':
        PhosphorIconsRegular.dotsThreeOutlineVertical,
    'dots-three-vertical': PhosphorIconsRegular.dotsThreeVertical,
    'flag': PhosphorIconsRegular.flag,
    'flag-banner': PhosphorIconsRegular.flagBanner,
    'grid-four': PhosphorIconsRegular.gridFour,
    'grid-nine': PhosphorIconsRegular.gridNine,
    'heart-straight': PhosphorIconsRegular.heartStraight,
    'house': PhosphorIconsRegular.house,
    'house-line': PhosphorIconsRegular.houseLine,
    'house-simple': PhosphorIconsRegular.houseSimple,
    'info': PhosphorIconsRegular.info,
    'layout': PhosphorIconsRegular.layout,
    'lightbulb': PhosphorIconsRegular.lightbulb,
    'lightbulb-filament': PhosphorIconsRegular.lightbulbFilament,
    'list': PhosphorIconsRegular.list,
    'list-bullets': PhosphorIconsRegular.listBullets,
    'list-checks': PhosphorIconsRegular.listChecks,
    'list-dashes': PhosphorIconsRegular.listDashes,
    'list-numbers': PhosphorIconsRegular.listNumbers,
    'list-plus': PhosphorIconsRegular.listPlus,
    'moon': PhosphorIconsRegular.moon,
    'question': PhosphorIconsRegular.question,
    'question-mark': PhosphorIconsRegular.questionMark,
    'rows': PhosphorIconsRegular.rows,
    'sparkle': PhosphorIconsRegular.sparkle,
    'square': PhosphorIconsRegular.square,
    'star': PhosphorIconsRegular.star,
    'star-four': PhosphorIconsRegular.starFour,
    'star-half': PhosphorIconsRegular.starHalf,
    'sun': PhosphorIconsRegular.sun,
    'tag': PhosphorIconsRegular.tag,
    'tag-simple': PhosphorIconsRegular.tagSimple,
    'target': PhosphorIconsRegular.target,
    'toggle-left': PhosphorIconsRegular.toggleLeft,
    'toggle-right': PhosphorIconsRegular.toggleRight,
    'trophy': PhosphorIconsRegular.trophy,
    'warning': PhosphorIconsRegular.warning,
    'warning-circle': PhosphorIconsRegular.warningCircle,
    'warning-diamond': PhosphorIconsRegular.warningDiamond,
    'warning-octagon': PhosphorIconsRegular.warningOctagon,

    // ─── Transaction Categories: Food & Dining ───
    'bowl-food': PhosphorIconsRegular.bowlFood,
    'bowl-steam': PhosphorIconsRegular.bowlSteam,
    'bread': PhosphorIconsRegular.bread,
    'cake': PhosphorIconsRegular.cake,
    'carrot': PhosphorIconsRegular.carrot,
    'cheese': PhosphorIconsRegular.cheese,
    'coffee': PhosphorIconsRegular.coffee,
    'cooking-pot': PhosphorIconsRegular.cookingPot,
    'egg': PhosphorIconsRegular.egg,
    'fork-knife': PhosphorIconsRegular.forkKnife,
    'hamburger': PhosphorIconsRegular.hamburger,
    'ice-cream': PhosphorIconsRegular.iceCream,
    'pizza': PhosphorIconsRegular.pizza,
    'popcorn': PhosphorIconsRegular.popcorn,
    'wine': PhosphorIconsRegular.wine,
    'beer-stein': PhosphorIconsRegular.beerStein,
    'coffee-bean': PhosphorIconsRegular.coffeeBean,

    // ─── Transaction Categories: Transport & Travel ───
    'airplane': PhosphorIconsRegular.airplane,
    'airplane-in-flight': PhosphorIconsRegular.airplaneInFlight,
    'airplane-tilt': PhosphorIconsRegular.airplaneTilt,
    'bicycle': PhosphorIconsRegular.bicycle,
    'bus': PhosphorIconsRegular.bus,
    'car': PhosphorIconsRegular.car,
    'car-profile': PhosphorIconsRegular.carProfile,
    'car-simple': PhosphorIconsRegular.carSimple,
    'charging-station': PhosphorIconsRegular.chargingStation,
    'compass': PhosphorIconsRegular.compass,
    'gas-pump': PhosphorIconsRegular.gasPump,
    'globe': PhosphorIconsRegular.globe,
    'globe-simple': PhosphorIconsRegular.globeSimple,
    'map-pin': PhosphorIconsRegular.mapPin,
    'map-pin-line': PhosphorIconsRegular.mapPinLine,
    'map-trifold': PhosphorIconsRegular.mapTrifold,
    'motorcycle': PhosphorIconsRegular.motorcycle,
    'navigation-arrow': PhosphorIconsRegular.navigationArrow,
    'sailboat': PhosphorIconsRegular.sailboat,
    'scooter': PhosphorIconsRegular.scooter,
    'steering-wheel': PhosphorIconsRegular.steeringWheel,
    'subway': PhosphorIconsRegular.subway,
    'suitcase': PhosphorIconsRegular.suitcase,
    'suitcase-rolling': PhosphorIconsRegular.suitcaseRolling,
    'suitcase-simple': PhosphorIconsRegular.suitcaseSimple,
    'taxi': PhosphorIconsRegular.taxi,
    'train': PhosphorIconsRegular.train,
    'train-simple': PhosphorIconsRegular.trainSimple,
    'tram': PhosphorIconsRegular.tram,
    'truck': PhosphorIconsRegular.truck,
    'van': PhosphorIconsRegular.van,

    // ─── Transaction Categories: Bills & Utilities ───
    'drop': PhosphorIconsRegular.drop,
    'drop-half': PhosphorIconsRegular.dropHalf,
    'drop-simple': PhosphorIconsRegular.dropSimple,
    'lightning': PhosphorIconsRegular.lightning,
    'lightning-a': PhosphorIconsRegular.lightningA,
    'lightning-slash': PhosphorIconsRegular.lightningSlash,
    'phone': PhosphorIconsRegular.phone,
    'phone-call': PhosphorIconsRegular.phoneCall,
    'newspaper': PhosphorIconsRegular.newspaper,
    'television': PhosphorIconsRegular.television,
    'television-simple': PhosphorIconsRegular.televisionSimple,
    'wifi-high': PhosphorIconsRegular.wifiHigh,
    'wifi-medium': PhosphorIconsRegular.wifiMedium,
    'wifi-low': PhosphorIconsRegular.wifiLow,
    'wifi-none': PhosphorIconsRegular.wifiNone,
    'cell-signal-full': PhosphorIconsRegular.cellSignalFull,
    'cell-signal-high': PhosphorIconsRegular.cellSignalHigh,
    'cell-signal-medium': PhosphorIconsRegular.cellSignalMedium,
    'cell-signal-low': PhosphorIconsRegular.cellSignalLow,
    'cell-signal-none': PhosphorIconsRegular.cellSignalNone,

    // ─── Transaction Categories: Entertainment ───
    'confetti': PhosphorIconsRegular.confetti,
    'film-slate': PhosphorIconsRegular.filmSlate,
    'film-strip': PhosphorIconsRegular.filmStrip,
    'game-controller': PhosphorIconsRegular.gameController,
    'guitar': PhosphorIconsRegular.guitar,
    'headphones': PhosphorIconsRegular.headphones,
    'headset': PhosphorIconsRegular.headset,
    'microphone': PhosphorIconsRegular.microphone,
    'music-note': PhosphorIconsRegular.musicNote,
    'music-note-simple': PhosphorIconsRegular.musicNoteSimple,
    'music-notes': PhosphorIconsRegular.musicNotes,
    'ticket': PhosphorIconsRegular.ticket,

    // ─── Transaction Categories: Health & Medical ───
    'first-aid': PhosphorIconsRegular.firstAid,
    'first-aid-kit': PhosphorIconsRegular.firstAidKit,
    'heart': PhosphorIconsRegular.heart,
    'heartbeat': PhosphorIconsRegular.heartbeat,
    'hospital': PhosphorIconsRegular.hospital,
    'pill': PhosphorIconsRegular.pill,
    'pulse': PhosphorIconsRegular.pulse,
    'stethoscope': PhosphorIconsRegular.stethoscope,
    'syringe': PhosphorIconsRegular.syringe,
    'thermometer': PhosphorIconsRegular.thermometer,
    'thermometer-simple': PhosphorIconsRegular.thermometerSimple,

    // ─── Transaction Categories: Shopping & Retail ───
    'bag': PhosphorIconsRegular.bag,
    'bag-simple': PhosphorIconsRegular.bagSimple,
    'gift': PhosphorIconsRegular.gift,
    'handbag': PhosphorIconsRegular.handbag,
    'handbag-simple': PhosphorIconsRegular.handbagSimple,

    // ─── Transaction Categories: Housing & Home ───
    'building': PhosphorIconsRegular.building,
    'building-apartment': PhosphorIconsRegular.buildingApartment,
    'building-office': PhosphorIconsRegular.buildingOffice,
    'buildings': PhosphorIconsRegular.buildings,
    'garage': PhosphorIconsRegular.garage,
    'lamp': PhosphorIconsRegular.lamp,
    'toolbox': PhosphorIconsRegular.toolbox,
    'wrench': PhosphorIconsRegular.wrench,

    // ─── Transaction Categories: Clothing & Fashion ───
    'boot': PhosphorIconsRegular.boot,
    'dress': PhosphorIconsRegular.dress,
    'high-heel': PhosphorIconsRegular.highHeel,
    'hoodie': PhosphorIconsRegular.hoodie,
    'sneaker': PhosphorIconsRegular.sneaker,
    't-shirt': PhosphorIconsRegular.tShirt,

    // ─── Transaction Categories: Education ───
    'book': PhosphorIconsRegular.book,
    'book-open': PhosphorIconsRegular.bookOpen,
    'book-open-text': PhosphorIconsRegular.bookOpenText,
    'books': PhosphorIconsRegular.books,
    'graduation-cap': PhosphorIconsRegular.graduationCap,
    'student': PhosphorIconsRegular.student,

    // ─── Transaction Categories: Family & Pets ───
    'baby': PhosphorIconsRegular.baby,
    'baby-carriage': PhosphorIconsRegular.babyCarriage,
    'bird': PhosphorIconsRegular.bird,
    'cat': PhosphorIconsRegular.cat,
    'dog': PhosphorIconsRegular.dog,
    'paw-print': PhosphorIconsRegular.pawPrint,

    // ─── Transaction Categories: Salary & Business ───
    'briefcase': PhosphorIconsRegular.briefcase,
    'briefcase-metal': PhosphorIconsRegular.briefcaseMetal,

    // ─── Transaction Categories: Sports & Fitness ───
    'barbell': PhosphorIconsRegular.barbell,
    'person-simple-bike': PhosphorIconsRegular.personSimpleBike,
    'person-simple-run': PhosphorIconsRegular.personSimpleRun,
    'person-simple-walk': PhosphorIconsRegular.personSimpleWalk,

    // ─── Transaction Categories: Nature ───
    'flower': PhosphorIconsRegular.flower,
    'flower-lotus': PhosphorIconsRegular.flowerLotus,
    'flower-tulip': PhosphorIconsRegular.flowerTulip,
    'leaf': PhosphorIconsRegular.leaf,
    'plant': PhosphorIconsRegular.plant,
    'tree': PhosphorIconsRegular.tree,

    // ─── Files & Data ───
    'file': PhosphorIconsRegular.file,
    'file-audio': PhosphorIconsRegular.fileAudio,
    'file-csv': PhosphorIconsRegular.fileCsv,
    'file-dashed': PhosphorIconsRegular.fileDashed,
    'file-doc': PhosphorIconsRegular.fileDoc,
    'file-image': PhosphorIconsRegular.fileImage,
    'file-minus': PhosphorIconsRegular.fileMinus,
    'file-pdf': PhosphorIconsRegular.filePdf,
    'file-plus': PhosphorIconsRegular.filePlus,
    'file-sql': PhosphorIconsRegular.fileSql,
    'file-text': PhosphorIconsRegular.fileText,
    'file-xls': PhosphorIconsRegular.fileXls,
    'files': PhosphorIconsRegular.files,
    'folder': PhosphorIconsRegular.folder,
    'folder-minus': PhosphorIconsRegular.folderMinus,
    'folder-open': PhosphorIconsRegular.folderOpen,
    'folder-plus': PhosphorIconsRegular.folderPlus,
    'folder-simple': PhosphorIconsRegular.folderSimple,
    'folder-user': PhosphorIconsRegular.folderUser,
    'folders': PhosphorIconsRegular.folders,

    // ─── Devices ───
    'desktop': PhosphorIconsRegular.desktop,
    'device-mobile': PhosphorIconsRegular.deviceMobile,
    'device-tablet': PhosphorIconsRegular.deviceTablet,
    'devices': PhosphorIconsRegular.devices,
    'laptop': PhosphorIconsRegular.laptop,
    'monitor': PhosphorIconsRegular.monitor,

    // ─── Brands & Social ───
    'apple-logo': PhosphorIconsRegular.appleLogo,
    'google-logo': PhosphorIconsRegular.googleLogo,
    'google-play-logo': PhosphorIconsRegular.googlePlayLogo,
    'paypal-logo': PhosphorIconsRegular.paypalLogo,
    'stripe-logo': PhosphorIconsRegular.stripeLogo,

    // ─── Cloud & Sync ───
    'cloud': PhosphorIconsRegular.cloud,
    'cloud-arrow-down': PhosphorIconsRegular.cloudArrowDown,
    'cloud-arrow-up': PhosphorIconsRegular.cloudArrowUp,
    'cloud-check': PhosphorIconsRegular.cloudCheck,
    'cloud-slash': PhosphorIconsRegular.cloudSlash,

    // ─── Misc ───
    'camera': PhosphorIconsRegular.camera,
    'database': PhosphorIconsRegular.database,
    'handshake': PhosphorIconsRegular.handshake,
    'image': PhosphorIconsRegular.image,
    'images': PhosphorIconsRegular.images,
    'image-square': PhosphorIconsRegular.imageSquare,
    'printer': PhosphorIconsRegular.printer,
    'radio-button': PhosphorIconsRegular.radioButton,
    'ruler': PhosphorIconsRegular.ruler,
    'scissors': PhosphorIconsRegular.scissors,
  };

  static Map<String, PhosphorIconData> get boldIcons => {
    // ─── Finance & Money ───
    'bank': PhosphorIconsBold.bank,
    'barcode': PhosphorIconsBold.barcode,
    'calculator': PhosphorIconsBold.calculator,
    'cash-register': PhosphorIconsBold.cashRegister,
    'coin': PhosphorIconsBold.coin,
    'coin-vertical': PhosphorIconsBold.coinVertical,
    'coins': PhosphorIconsBold.coins,
    'contactless-payment': PhosphorIconsBold.contactlessPayment,
    'credit-card': PhosphorIconsBold.creditCard,
    'currency-btc': PhosphorIconsBold.currencyBtc,
    'currency-circle-dollar': PhosphorIconsBold.currencyCircleDollar,
    'currency-dollar': PhosphorIconsBold.currencyDollar,
    'currency-dollar-simple': PhosphorIconsBold.currencyDollarSimple,
    'currency-eur': PhosphorIconsBold.currencyEur,
    'currency-gbp': PhosphorIconsBold.currencyGbp,
    'currency-inr': PhosphorIconsBold.currencyInr,
    'currency-jpy': PhosphorIconsBold.currencyJpy,
    'hand-coins': PhosphorIconsBold.handCoins,
    'hand-deposit': PhosphorIconsBold.handDeposit,
    'hand-withdraw': PhosphorIconsBold.handWithdraw,
    'invoice': PhosphorIconsBold.invoice,
    'money': PhosphorIconsBold.money,
    'money-wavy': PhosphorIconsBold.moneyWavy,
    'percent': PhosphorIconsBold.percent,
    'piggy-bank': PhosphorIconsBold.piggyBank,
    'poker-chip': PhosphorIconsBold.pokerChip,
    'qr-code': PhosphorIconsBold.qrCode,
    'receipt': PhosphorIconsBold.receipt,
    'receipt-x': PhosphorIconsBold.receiptX,
    'shopping-bag': PhosphorIconsBold.shoppingBag,
    'shopping-bag-open': PhosphorIconsBold.shoppingBagOpen,
    'shopping-cart': PhosphorIconsBold.shoppingCart,
    'shopping-cart-simple': PhosphorIconsBold.shoppingCartSimple,
    'storefront': PhosphorIconsBold.storefront,
    'tip-jar': PhosphorIconsBold.tipJar,
    'treasure-chest': PhosphorIconsBold.treasureChest,
    'trolley': PhosphorIconsBold.trolley,
    'vault': PhosphorIconsBold.vault,
    'wallet': PhosphorIconsBold.wallet,

    // ─── Charts & Statistics ───
    'chart-bar': PhosphorIconsBold.chartBar,
    'chart-bar-horizontal': PhosphorIconsBold.chartBarHorizontal,
    'chart-donut': PhosphorIconsBold.chartDonut,
    'chart-line': PhosphorIconsBold.chartLine,
    'chart-line-down': PhosphorIconsBold.chartLineDown,
    'chart-line-up': PhosphorIconsBold.chartLineUp,
    'chart-pie': PhosphorIconsBold.chartPie,
    'chart-pie-slice': PhosphorIconsBold.chartPieSlice,
    'chart-polar': PhosphorIconsBold.chartPolar,
    'chart-scatter': PhosphorIconsBold.chartScatter,
    'graph': PhosphorIconsBold.graph,
    'presentation-chart': PhosphorIconsBold.presentationChart,
    'projector-screen-chart': PhosphorIconsBold.projectorScreenChart,
    'ranking': PhosphorIconsBold.ranking,
    'trend-down': PhosphorIconsBold.trendDown,
    'trend-up': PhosphorIconsBold.trendUp,

    // ─── Navigation & Arrows (essential) ───
    'arrow-arc-left': PhosphorIconsBold.arrowArcLeft,
    'arrow-arc-right': PhosphorIconsBold.arrowArcRight,
    'arrow-circle-down': PhosphorIconsBold.arrowCircleDown,
    'arrow-circle-left': PhosphorIconsBold.arrowCircleLeft,
    'arrow-circle-right': PhosphorIconsBold.arrowCircleRight,
    'arrow-circle-up': PhosphorIconsBold.arrowCircleUp,
    'arrow-clockwise': PhosphorIconsBold.arrowClockwise,
    'arrow-counter-clockwise': PhosphorIconsBold.arrowCounterClockwise,
    'arrow-down': PhosphorIconsBold.arrowDown,
    'arrow-left': PhosphorIconsBold.arrowLeft,
    'arrow-right': PhosphorIconsBold.arrowRight,
    'arrow-up': PhosphorIconsBold.arrowUp,
    'arrows-clockwise': PhosphorIconsBold.arrowsClockwise,
    'arrows-counter-clockwise': PhosphorIconsBold.arrowsCounterClockwise,
    'arrows-down-up': PhosphorIconsBold.arrowsDownUp,
    'arrows-horizontal': PhosphorIconsBold.arrowsHorizontal,
    'arrows-left-right': PhosphorIconsBold.arrowsLeftRight,
    'arrows-merge': PhosphorIconsBold.arrowsMerge,
    'arrows-split': PhosphorIconsBold.arrowsSplit,
    'arrows-vertical': PhosphorIconsBold.arrowsVertical,
    'caret-circle-down': PhosphorIconsBold.caretCircleDown,
    'caret-circle-left': PhosphorIconsBold.caretCircleLeft,
    'caret-circle-right': PhosphorIconsBold.caretCircleRight,
    'caret-circle-up': PhosphorIconsBold.caretCircleUp,
    'caret-circle-up-down': PhosphorIconsBold.caretCircleUpDown,
    'caret-down': PhosphorIconsBold.caretDown,
    'caret-left': PhosphorIconsBold.caretLeft,
    'caret-right': PhosphorIconsBold.caretRight,
    'caret-up': PhosphorIconsBold.caretUp,
    'caret-up-down': PhosphorIconsBold.caretUpDown,
    'sign-in': PhosphorIconsBold.signIn,
    'sign-out': PhosphorIconsBold.signOut,
    'swap': PhosphorIconsBold.swap,

    // ─── Actions (common UI) ───
    'check': PhosphorIconsBold.check,
    'check-circle': PhosphorIconsBold.checkCircle,
    'check-fat': PhosphorIconsBold.checkFat,
    'check-square': PhosphorIconsBold.checkSquare,
    'check-square-offset': PhosphorIconsBold.checkSquareOffset,
    'checks': PhosphorIconsBold.checks,
    'clipboard': PhosphorIconsBold.clipboard,
    'clipboard-text': PhosphorIconsBold.clipboardText,
    'copy': PhosphorIconsBold.copy,
    'copy-simple': PhosphorIconsBold.copySimple,
    'download': PhosphorIconsBold.download,
    'download-simple': PhosphorIconsBold.downloadSimple,
    'export': PhosphorIconsBold.export,
    'eye': PhosphorIconsBold.eye,
    'eye-closed': PhosphorIconsBold.eyeClosed,
    'eye-slash': PhosphorIconsBold.eyeSlash,
    'file-arrow-down': PhosphorIconsBold.fileArrowDown,
    'file-arrow-up': PhosphorIconsBold.fileArrowUp,
    'funnel': PhosphorIconsBold.funnel,
    'funnel-simple': PhosphorIconsBold.funnelSimple,
    'funnel-simple-x': PhosphorIconsBold.funnelSimpleX,
    'funnel-x': PhosphorIconsBold.funnelX,
    'link': PhosphorIconsBold.link,
    'link-break': PhosphorIconsBold.linkBreak,
    'link-simple': PhosphorIconsBold.linkSimple,
    'link-simple-break': PhosphorIconsBold.linkSimpleBreak,
    'magnifying-glass': PhosphorIconsBold.magnifyingGlass,
    'magnifying-glass-minus': PhosphorIconsBold.magnifyingGlassMinus,
    'magnifying-glass-plus': PhosphorIconsBold.magnifyingGlassPlus,
    'minus': PhosphorIconsBold.minus,
    'minus-circle': PhosphorIconsBold.minusCircle,
    'minus-square': PhosphorIconsBold.minusSquare,
    'pencil': PhosphorIconsBold.pencil,
    'pencil-circle': PhosphorIconsBold.pencilCircle,
    'pencil-line': PhosphorIconsBold.pencilLine,
    'pencil-simple': PhosphorIconsBold.pencilSimple,
    'plus': PhosphorIconsBold.plus,
    'plus-circle': PhosphorIconsBold.plusCircle,
    'plus-minus': PhosphorIconsBold.plusMinus,
    'plus-square': PhosphorIconsBold.plusSquare,
    'share': PhosphorIconsBold.share,
    'share-fat': PhosphorIconsBold.shareFat,
    'share-network': PhosphorIconsBold.shareNetwork,
    'sort-ascending': PhosphorIconsBold.sortAscending,
    'sort-descending': PhosphorIconsBold.sortDescending,
    'trash': PhosphorIconsBold.trash,
    'trash-simple': PhosphorIconsBold.trashSimple,
    'upload': PhosphorIconsBold.upload,
    'upload-simple': PhosphorIconsBold.uploadSimple,
    'x': PhosphorIconsBold.x,
    'x-circle': PhosphorIconsBold.xCircle,
    'x-square': PhosphorIconsBold.xSquare,

    // ─── Security & Authentication ───
    'fingerprint': PhosphorIconsBold.fingerprint,
    'fingerprint-simple': PhosphorIconsBold.fingerprintSimple,
    'key': PhosphorIconsBold.key,
    'lock': PhosphorIconsBold.lock,
    'lock-key': PhosphorIconsBold.lockKey,
    'lock-key-open': PhosphorIconsBold.lockKeyOpen,
    'lock-open': PhosphorIconsBold.lockOpen,
    'lock-simple': PhosphorIconsBold.lockSimple,
    'lock-simple-open': PhosphorIconsBold.lockSimpleOpen,
    'scan': PhosphorIconsBold.scan,
    'shield': PhosphorIconsBold.shield,
    'shield-check': PhosphorIconsBold.shieldCheck,
    'shield-star': PhosphorIconsBold.shieldStar,
    'shield-warning': PhosphorIconsBold.shieldWarning,

    // ─── Settings & Profile ───
    'gear': PhosphorIconsBold.gear,
    'gear-fine': PhosphorIconsBold.gearFine,
    'gear-six': PhosphorIconsBold.gearSix,
    'identification-badge': PhosphorIconsBold.identificationBadge,
    'identification-card': PhosphorIconsBold.identificationCard,
    'palette': PhosphorIconsBold.palette,
    'sliders': PhosphorIconsBold.sliders,
    'sliders-horizontal': PhosphorIconsBold.slidersHorizontal,
    'translate': PhosphorIconsBold.translate,
    'user': PhosphorIconsBold.user,
    'user-check': PhosphorIconsBold.userCheck,
    'user-circle': PhosphorIconsBold.userCircle,
    'user-circle-gear': PhosphorIconsBold.userCircleGear,
    'user-focus': PhosphorIconsBold.userFocus,
    'user-gear': PhosphorIconsBold.userGear,
    'user-list': PhosphorIconsBold.userList,
    'user-minus': PhosphorIconsBold.userMinus,
    'user-plus': PhosphorIconsBold.userPlus,
    'user-switch': PhosphorIconsBold.userSwitch,
    'users': PhosphorIconsBold.users,
    'users-three': PhosphorIconsBold.usersThree,
    'users-four': PhosphorIconsBold.usersFour,

    // ─── Notifications & Communication ───
    'bell': PhosphorIconsBold.bell,
    'bell-ringing': PhosphorIconsBold.bellRinging,
    'bell-simple': PhosphorIconsBold.bellSimple,
    'bell-simple-ringing': PhosphorIconsBold.bellSimpleRinging,
    'bell-simple-slash': PhosphorIconsBold.bellSimpleSlash,
    'bell-slash': PhosphorIconsBold.bellSlash,
    'envelope': PhosphorIconsBold.envelope,
    'envelope-simple': PhosphorIconsBold.envelopeSimple,
    'notification': PhosphorIconsBold.notification,

    // ─── Date & Time ───
    'calendar': PhosphorIconsBold.calendar,
    'calendar-blank': PhosphorIconsBold.calendarBlank,
    'calendar-check': PhosphorIconsBold.calendarCheck,
    'calendar-dot': PhosphorIconsBold.calendarDot,
    'calendar-dots': PhosphorIconsBold.calendarDots,
    'calendar-heart': PhosphorIconsBold.calendarHeart,
    'calendar-minus': PhosphorIconsBold.calendarMinus,
    'calendar-plus': PhosphorIconsBold.calendarPlus,
    'calendar-x': PhosphorIconsBold.calendarX,
    'clock': PhosphorIconsBold.clock,
    'clock-afternoon': PhosphorIconsBold.clockAfternoon,
    'clock-clockwise': PhosphorIconsBold.clockClockwise,
    'clock-counter-clockwise': PhosphorIconsBold.clockCounterClockwise,
    'hourglass': PhosphorIconsBold.hourglass,
    'hourglass-high': PhosphorIconsBold.hourglassHigh,
    'hourglass-low': PhosphorIconsBold.hourglassLow,
    'hourglass-medium': PhosphorIconsBold.hourglassMedium,
    'hourglass-simple': PhosphorIconsBold.hourglassSimple,
    'timer': PhosphorIconsBold.timer,

    // ─── UI & Layout ───
    'bookmark': PhosphorIconsBold.bookmark,
    'bookmark-simple': PhosphorIconsBold.bookmarkSimple,
    'bookmarks': PhosphorIconsBold.bookmarks,
    'bookmarks-simple': PhosphorIconsBold.bookmarksSimple,
    'circle': PhosphorIconsBold.circle,
    'circle-dashed': PhosphorIconsBold.circleDashed,
    'circle-half': PhosphorIconsBold.circleHalf,
    'columns': PhosphorIconsBold.columns,
    'crown': PhosphorIconsBold.crown,
    'crown-simple': PhosphorIconsBold.crownSimple,
    'diamond': PhosphorIconsBold.diamond,
    'dots-nine': PhosphorIconsBold.dotsNine,
    'dots-six': PhosphorIconsBold.dotsSix,
    'dots-six-vertical': PhosphorIconsBold.dotsSixVertical,
    'dots-three': PhosphorIconsBold.dotsThree,
    'dots-three-circle': PhosphorIconsBold.dotsThreeCircle,
    'dots-three-circle-vertical': PhosphorIconsBold.dotsThreeCircleVertical,
    'dots-three-outline': PhosphorIconsBold.dotsThreeOutline,
    'dots-three-outline-vertical': PhosphorIconsBold.dotsThreeOutlineVertical,
    'dots-three-vertical': PhosphorIconsBold.dotsThreeVertical,
    'flag': PhosphorIconsBold.flag,
    'flag-banner': PhosphorIconsBold.flagBanner,
    'grid-four': PhosphorIconsBold.gridFour,
    'grid-nine': PhosphorIconsBold.gridNine,
    'heart-straight': PhosphorIconsBold.heartStraight,
    'house': PhosphorIconsBold.house,
    'house-line': PhosphorIconsBold.houseLine,
    'house-simple': PhosphorIconsBold.houseSimple,
    'info': PhosphorIconsBold.info,
    'layout': PhosphorIconsBold.layout,
    'lightbulb': PhosphorIconsBold.lightbulb,
    'lightbulb-filament': PhosphorIconsBold.lightbulbFilament,
    'list': PhosphorIconsBold.list,
    'list-bullets': PhosphorIconsBold.listBullets,
    'list-checks': PhosphorIconsBold.listChecks,
    'list-dashes': PhosphorIconsBold.listDashes,
    'list-numbers': PhosphorIconsBold.listNumbers,
    'list-plus': PhosphorIconsBold.listPlus,
    'moon': PhosphorIconsBold.moon,
    'question': PhosphorIconsBold.question,
    'question-mark': PhosphorIconsBold.questionMark,
    'rows': PhosphorIconsBold.rows,
    'sparkle': PhosphorIconsBold.sparkle,
    'square': PhosphorIconsBold.square,
    'star': PhosphorIconsBold.star,
    'star-four': PhosphorIconsBold.starFour,
    'star-half': PhosphorIconsBold.starHalf,
    'sun': PhosphorIconsBold.sun,
    'tag': PhosphorIconsBold.tag,
    'tag-simple': PhosphorIconsBold.tagSimple,
    'target': PhosphorIconsBold.target,
    'toggle-left': PhosphorIconsBold.toggleLeft,
    'toggle-right': PhosphorIconsBold.toggleRight,
    'trophy': PhosphorIconsBold.trophy,
    'warning': PhosphorIconsBold.warning,
    'warning-circle': PhosphorIconsBold.warningCircle,
    'warning-diamond': PhosphorIconsBold.warningDiamond,
    'warning-octagon': PhosphorIconsBold.warningOctagon,

    // ─── Transaction Categories: Food & Dining ───
    'bowl-food': PhosphorIconsBold.bowlFood,
    'bowl-steam': PhosphorIconsBold.bowlSteam,
    'bread': PhosphorIconsBold.bread,
    'cake': PhosphorIconsBold.cake,
    'carrot': PhosphorIconsBold.carrot,
    'cheese': PhosphorIconsBold.cheese,
    'coffee': PhosphorIconsBold.coffee,
    'cooking-pot': PhosphorIconsBold.cookingPot,
    'egg': PhosphorIconsBold.egg,
    'fork-knife': PhosphorIconsBold.forkKnife,
    'hamburger': PhosphorIconsBold.hamburger,
    'ice-cream': PhosphorIconsBold.iceCream,
    'pizza': PhosphorIconsBold.pizza,
    'popcorn': PhosphorIconsBold.popcorn,
    'wine': PhosphorIconsBold.wine,
    'beer-stein': PhosphorIconsBold.beerStein,
    'coffee-bean': PhosphorIconsBold.coffeeBean,

    // ─── Transaction Categories: Transport & Travel ───
    'airplane': PhosphorIconsBold.airplane,
    'airplane-in-flight': PhosphorIconsBold.airplaneInFlight,
    'airplane-tilt': PhosphorIconsBold.airplaneTilt,
    'bicycle': PhosphorIconsBold.bicycle,
    'bus': PhosphorIconsBold.bus,
    'car': PhosphorIconsBold.car,
    'car-profile': PhosphorIconsBold.carProfile,
    'car-simple': PhosphorIconsBold.carSimple,
    'charging-station': PhosphorIconsBold.chargingStation,
    'compass': PhosphorIconsBold.compass,
    'gas-pump': PhosphorIconsBold.gasPump,
    'globe': PhosphorIconsBold.globe,
    'globe-simple': PhosphorIconsBold.globeSimple,
    'map-pin': PhosphorIconsBold.mapPin,
    'map-pin-line': PhosphorIconsBold.mapPinLine,
    'map-trifold': PhosphorIconsBold.mapTrifold,
    'motorcycle': PhosphorIconsBold.motorcycle,
    'navigation-arrow': PhosphorIconsBold.navigationArrow,
    'sailboat': PhosphorIconsBold.sailboat,
    'scooter': PhosphorIconsBold.scooter,
    'steering-wheel': PhosphorIconsBold.steeringWheel,
    'subway': PhosphorIconsBold.subway,
    'suitcase': PhosphorIconsBold.suitcase,
    'suitcase-rolling': PhosphorIconsBold.suitcaseRolling,
    'suitcase-simple': PhosphorIconsBold.suitcaseSimple,
    'taxi': PhosphorIconsBold.taxi,
    'train': PhosphorIconsBold.train,
    'train-simple': PhosphorIconsBold.trainSimple,
    'tram': PhosphorIconsBold.tram,
    'truck': PhosphorIconsBold.truck,
    'van': PhosphorIconsBold.van,

    // ─── Transaction Categories: Bills & Utilities ───
    'drop': PhosphorIconsBold.drop,
    'drop-half': PhosphorIconsBold.dropHalf,
    'drop-simple': PhosphorIconsBold.dropSimple,
    'lightning': PhosphorIconsBold.lightning,
    'lightning-a': PhosphorIconsBold.lightningA,
    'lightning-slash': PhosphorIconsBold.lightningSlash,
    'phone': PhosphorIconsBold.phone,
    'phone-call': PhosphorIconsBold.phoneCall,
    'newspaper': PhosphorIconsBold.newspaper,
    'television': PhosphorIconsBold.television,
    'television-simple': PhosphorIconsBold.televisionSimple,
    'wifi-high': PhosphorIconsBold.wifiHigh,
    'wifi-medium': PhosphorIconsBold.wifiMedium,
    'wifi-low': PhosphorIconsBold.wifiLow,
    'wifi-none': PhosphorIconsBold.wifiNone,
    'cell-signal-full': PhosphorIconsBold.cellSignalFull,
    'cell-signal-high': PhosphorIconsBold.cellSignalHigh,
    'cell-signal-medium': PhosphorIconsBold.cellSignalMedium,
    'cell-signal-low': PhosphorIconsBold.cellSignalLow,
    'cell-signal-none': PhosphorIconsBold.cellSignalNone,

    // ─── Transaction Categories: Entertainment ───
    'confetti': PhosphorIconsBold.confetti,
    'film-slate': PhosphorIconsBold.filmSlate,
    'film-strip': PhosphorIconsBold.filmStrip,
    'game-controller': PhosphorIconsBold.gameController,
    'guitar': PhosphorIconsBold.guitar,
    'headphones': PhosphorIconsBold.headphones,
    'headset': PhosphorIconsBold.headset,
    'microphone': PhosphorIconsBold.microphone,
    'music-note': PhosphorIconsBold.musicNote,
    'music-note-simple': PhosphorIconsBold.musicNoteSimple,
    'music-notes': PhosphorIconsBold.musicNotes,
    'ticket': PhosphorIconsBold.ticket,

    // ─── Transaction Categories: Health & Medical ───
    'first-aid': PhosphorIconsBold.firstAid,
    'first-aid-kit': PhosphorIconsBold.firstAidKit,
    'heart': PhosphorIconsBold.heart,
    'heartbeat': PhosphorIconsBold.heartbeat,
    'hospital': PhosphorIconsBold.hospital,
    'pill': PhosphorIconsBold.pill,
    'pulse': PhosphorIconsBold.pulse,
    'stethoscope': PhosphorIconsBold.stethoscope,
    'syringe': PhosphorIconsBold.syringe,
    'thermometer': PhosphorIconsBold.thermometer,
    'thermometer-simple': PhosphorIconsBold.thermometerSimple,

    // ─── Transaction Categories: Shopping & Retail ───
    'bag': PhosphorIconsBold.bag,
    'bag-simple': PhosphorIconsBold.bagSimple,
    'gift': PhosphorIconsBold.gift,
    'handbag': PhosphorIconsBold.handbag,
    'handbag-simple': PhosphorIconsBold.handbagSimple,

    // ─── Transaction Categories: Housing & Home ───
    'building': PhosphorIconsBold.building,
    'building-apartment': PhosphorIconsBold.buildingApartment,
    'building-office': PhosphorIconsBold.buildingOffice,
    'buildings': PhosphorIconsBold.buildings,
    'garage': PhosphorIconsBold.garage,
    'lamp': PhosphorIconsBold.lamp,
    'toolbox': PhosphorIconsBold.toolbox,
    'wrench': PhosphorIconsBold.wrench,

    // ─── Transaction Categories: Clothing & Fashion ───
    'boot': PhosphorIconsBold.boot,
    'dress': PhosphorIconsBold.dress,
    'high-heel': PhosphorIconsBold.highHeel,
    'hoodie': PhosphorIconsBold.hoodie,
    'sneaker': PhosphorIconsBold.sneaker,
    't-shirt': PhosphorIconsBold.tShirt,

    // ─── Transaction Categories: Education ───
    'book': PhosphorIconsBold.book,
    'book-open': PhosphorIconsBold.bookOpen,
    'book-open-text': PhosphorIconsBold.bookOpenText,
    'books': PhosphorIconsBold.books,
    'graduation-cap': PhosphorIconsBold.graduationCap,
    'student': PhosphorIconsBold.student,

    // ─── Transaction Categories: Family & Pets ───
    'baby': PhosphorIconsBold.baby,
    'baby-carriage': PhosphorIconsBold.babyCarriage,
    'bird': PhosphorIconsBold.bird,
    'cat': PhosphorIconsBold.cat,
    'dog': PhosphorIconsBold.dog,
    'paw-print': PhosphorIconsBold.pawPrint,

    // ─── Transaction Categories: Salary & Business ───
    'briefcase': PhosphorIconsBold.briefcase,
    'briefcase-metal': PhosphorIconsBold.briefcaseMetal,

    // ─── Transaction Categories: Sports & Fitness ───
    'barbell': PhosphorIconsBold.barbell,
    'person-simple-bike': PhosphorIconsBold.personSimpleBike,
    'person-simple-run': PhosphorIconsBold.personSimpleRun,
    'person-simple-walk': PhosphorIconsBold.personSimpleWalk,

    // ─── Transaction Categories: Nature ───
    'flower': PhosphorIconsBold.flower,
    'flower-lotus': PhosphorIconsBold.flowerLotus,
    'flower-tulip': PhosphorIconsBold.flowerTulip,
    'leaf': PhosphorIconsBold.leaf,
    'plant': PhosphorIconsBold.plant,
    'tree': PhosphorIconsBold.tree,

    // ─── Files & Data ───
    'file': PhosphorIconsBold.file,
    'file-audio': PhosphorIconsBold.fileAudio,
    'file-csv': PhosphorIconsBold.fileCsv,
    'file-dashed': PhosphorIconsBold.fileDashed,
    'file-doc': PhosphorIconsBold.fileDoc,
    'file-image': PhosphorIconsBold.fileImage,
    'file-minus': PhosphorIconsBold.fileMinus,
    'file-pdf': PhosphorIconsBold.filePdf,
    'file-plus': PhosphorIconsBold.filePlus,
    'file-sql': PhosphorIconsBold.fileSql,
    'file-text': PhosphorIconsBold.fileText,
    'file-xls': PhosphorIconsBold.fileXls,
    'files': PhosphorIconsBold.files,
    'folder': PhosphorIconsBold.folder,
    'folder-minus': PhosphorIconsBold.folderMinus,
    'folder-open': PhosphorIconsBold.folderOpen,
    'folder-plus': PhosphorIconsBold.folderPlus,
    'folder-simple': PhosphorIconsBold.folderSimple,
    'folder-user': PhosphorIconsBold.folderUser,
    'folders': PhosphorIconsBold.folders,

    // ─── Devices ───
    'desktop': PhosphorIconsBold.desktop,
    'device-mobile': PhosphorIconsBold.deviceMobile,
    'device-tablet': PhosphorIconsBold.deviceTablet,
    'devices': PhosphorIconsBold.devices,
    'laptop': PhosphorIconsBold.laptop,
    'monitor': PhosphorIconsBold.monitor,

    // ─── Brands & Social ───
    'apple-logo': PhosphorIconsBold.appleLogo,
    'google-logo': PhosphorIconsBold.googleLogo,
    'google-play-logo': PhosphorIconsBold.googlePlayLogo,
    'paypal-logo': PhosphorIconsBold.paypalLogo,
    'stripe-logo': PhosphorIconsBold.stripeLogo,

    // ─── Cloud & Sync ───
    'cloud': PhosphorIconsBold.cloud,
    'cloud-arrow-down': PhosphorIconsBold.cloudArrowDown,
    'cloud-arrow-up': PhosphorIconsBold.cloudArrowUp,
    'cloud-check': PhosphorIconsBold.cloudCheck,
    'cloud-slash': PhosphorIconsBold.cloudSlash,

    // ─── Misc ───
    'camera': PhosphorIconsBold.camera,
    'database': PhosphorIconsBold.database,
    'handshake': PhosphorIconsBold.handshake,
    'image': PhosphorIconsBold.image,
    'images': PhosphorIconsBold.images,
    'image-square': PhosphorIconsBold.imageSquare,
    'printer': PhosphorIconsBold.printer,
    'radio-button': PhosphorIconsBold.radioButton,
    'ruler': PhosphorIconsBold.ruler,
    'scissors': PhosphorIconsBold.scissors,
  };

  static Map<String, PhosphorIconData> get fillIcons => {
    // ─── Finance & Money ───
    'bank': PhosphorIconsFill.bank,
    'barcode': PhosphorIconsFill.barcode,
    'calculator': PhosphorIconsFill.calculator,
    'cash-register': PhosphorIconsFill.cashRegister,
    'coin': PhosphorIconsFill.coin,
    'coin-vertical': PhosphorIconsFill.coinVertical,
    'coins': PhosphorIconsFill.coins,
    'contactless-payment': PhosphorIconsFill.contactlessPayment,
    'credit-card': PhosphorIconsFill.creditCard,
    'currency-btc': PhosphorIconsFill.currencyBtc,
    'currency-circle-dollar': PhosphorIconsFill.currencyCircleDollar,
    'currency-dollar': PhosphorIconsFill.currencyDollar,
    'currency-dollar-simple': PhosphorIconsFill.currencyDollarSimple,
    'currency-eur': PhosphorIconsFill.currencyEur,
    'currency-gbp': PhosphorIconsFill.currencyGbp,
    'currency-inr': PhosphorIconsFill.currencyInr,
    'currency-jpy': PhosphorIconsFill.currencyJpy,
    'hand-coins': PhosphorIconsFill.handCoins,
    'hand-deposit': PhosphorIconsFill.handDeposit,
    'hand-withdraw': PhosphorIconsFill.handWithdraw,
    'invoice': PhosphorIconsFill.invoice,
    'money': PhosphorIconsFill.money,
    'money-wavy': PhosphorIconsFill.moneyWavy,
    'percent': PhosphorIconsFill.percent,
    'piggy-bank': PhosphorIconsFill.piggyBank,
    'poker-chip': PhosphorIconsFill.pokerChip,
    'qr-code': PhosphorIconsFill.qrCode,
    'receipt': PhosphorIconsFill.receipt,
    'receipt-x': PhosphorIconsFill.receiptX,
    'shopping-bag': PhosphorIconsFill.shoppingBag,
    'shopping-bag-open': PhosphorIconsFill.shoppingBagOpen,
    'shopping-cart': PhosphorIconsFill.shoppingCart,
    'shopping-cart-simple': PhosphorIconsFill.shoppingCartSimple,
    'storefront': PhosphorIconsFill.storefront,
    'tip-jar': PhosphorIconsFill.tipJar,
    'treasure-chest': PhosphorIconsFill.treasureChest,
    'trolley': PhosphorIconsFill.trolley,
    'vault': PhosphorIconsFill.vault,
    'wallet': PhosphorIconsFill.wallet,

    // ─── Charts & Statistics ───
    'chart-bar': PhosphorIconsFill.chartBar,
    'chart-bar-horizontal': PhosphorIconsFill.chartBarHorizontal,
    'chart-donut': PhosphorIconsFill.chartDonut,
    'chart-line': PhosphorIconsFill.chartLine,
    'chart-line-down': PhosphorIconsFill.chartLineDown,
    'chart-line-up': PhosphorIconsFill.chartLineUp,
    'chart-pie': PhosphorIconsFill.chartPie,
    'chart-pie-slice': PhosphorIconsFill.chartPieSlice,
    'chart-polar': PhosphorIconsFill.chartPolar,
    'chart-scatter': PhosphorIconsFill.chartScatter,
    'graph': PhosphorIconsFill.graph,
    'presentation-chart': PhosphorIconsFill.presentationChart,
    'projector-screen-chart': PhosphorIconsFill.projectorScreenChart,
    'ranking': PhosphorIconsFill.ranking,
    'trend-down': PhosphorIconsFill.trendDown,
    'trend-up': PhosphorIconsFill.trendUp,

    // ─── Navigation & Arrows (essential) ───
    'arrow-arc-left': PhosphorIconsFill.arrowArcLeft,
    'arrow-arc-right': PhosphorIconsFill.arrowArcRight,
    'arrow-circle-down': PhosphorIconsFill.arrowCircleDown,
    'arrow-circle-left': PhosphorIconsFill.arrowCircleLeft,
    'arrow-circle-right': PhosphorIconsFill.arrowCircleRight,
    'arrow-circle-up': PhosphorIconsFill.arrowCircleUp,
    'arrow-clockwise': PhosphorIconsFill.arrowClockwise,
    'arrow-counter-clockwise': PhosphorIconsFill.arrowCounterClockwise,
    'arrow-down': PhosphorIconsFill.arrowDown,
    'arrow-left': PhosphorIconsFill.arrowLeft,
    'arrow-right': PhosphorIconsFill.arrowRight,
    'arrow-up': PhosphorIconsFill.arrowUp,
    'arrows-clockwise': PhosphorIconsFill.arrowsClockwise,
    'arrows-counter-clockwise': PhosphorIconsFill.arrowsCounterClockwise,
    'arrows-down-up': PhosphorIconsFill.arrowsDownUp,
    'arrows-horizontal': PhosphorIconsFill.arrowsHorizontal,
    'arrows-left-right': PhosphorIconsFill.arrowsLeftRight,
    'arrows-merge': PhosphorIconsFill.arrowsMerge,
    'arrows-split': PhosphorIconsFill.arrowsSplit,
    'arrows-vertical': PhosphorIconsFill.arrowsVertical,
    'caret-circle-down': PhosphorIconsFill.caretCircleDown,
    'caret-circle-left': PhosphorIconsFill.caretCircleLeft,
    'caret-circle-right': PhosphorIconsFill.caretCircleRight,
    'caret-circle-up': PhosphorIconsFill.caretCircleUp,
    'caret-circle-up-down': PhosphorIconsFill.caretCircleUpDown,
    'caret-down': PhosphorIconsFill.caretDown,
    'caret-left': PhosphorIconsFill.caretLeft,
    'caret-right': PhosphorIconsFill.caretRight,
    'caret-up': PhosphorIconsFill.caretUp,
    'caret-up-down': PhosphorIconsFill.caretUpDown,
    'sign-in': PhosphorIconsFill.signIn,
    'sign-out': PhosphorIconsFill.signOut,
    'swap': PhosphorIconsFill.swap,

    // ─── Actions (common UI) ───
    'check': PhosphorIconsFill.check,
    'check-circle': PhosphorIconsFill.checkCircle,
    'check-fat': PhosphorIconsFill.checkFat,
    'check-square': PhosphorIconsFill.checkSquare,
    'check-square-offset': PhosphorIconsFill.checkSquareOffset,
    'checks': PhosphorIconsFill.checks,
    'clipboard': PhosphorIconsFill.clipboard,
    'clipboard-text': PhosphorIconsFill.clipboardText,
    'copy': PhosphorIconsFill.copy,
    'copy-simple': PhosphorIconsFill.copySimple,
    'download': PhosphorIconsFill.download,
    'download-simple': PhosphorIconsFill.downloadSimple,
    'export': PhosphorIconsFill.export,
    'eye': PhosphorIconsFill.eye,
    'eye-closed': PhosphorIconsFill.eyeClosed,
    'eye-slash': PhosphorIconsFill.eyeSlash,
    'file-arrow-down': PhosphorIconsFill.fileArrowDown,
    'file-arrow-up': PhosphorIconsFill.fileArrowUp,
    'funnel': PhosphorIconsFill.funnel,
    'funnel-simple': PhosphorIconsFill.funnelSimple,
    'funnel-simple-x': PhosphorIconsFill.funnelSimpleX,
    'funnel-x': PhosphorIconsFill.funnelX,
    'link': PhosphorIconsFill.link,
    'link-break': PhosphorIconsFill.linkBreak,
    'link-simple': PhosphorIconsFill.linkSimple,
    'link-simple-break': PhosphorIconsFill.linkSimpleBreak,
    'magnifying-glass': PhosphorIconsFill.magnifyingGlass,
    'magnifying-glass-minus': PhosphorIconsFill.magnifyingGlassMinus,
    'magnifying-glass-plus': PhosphorIconsFill.magnifyingGlassPlus,
    'minus': PhosphorIconsFill.minus,
    'minus-circle': PhosphorIconsFill.minusCircle,
    'minus-square': PhosphorIconsFill.minusSquare,
    'pencil': PhosphorIconsFill.pencil,
    'pencil-circle': PhosphorIconsFill.pencilCircle,
    'pencil-line': PhosphorIconsFill.pencilLine,
    'pencil-simple': PhosphorIconsFill.pencilSimple,
    'plus': PhosphorIconsFill.plus,
    'plus-circle': PhosphorIconsFill.plusCircle,
    'plus-minus': PhosphorIconsFill.plusMinus,
    'plus-square': PhosphorIconsFill.plusSquare,
    'share': PhosphorIconsFill.share,
    'share-fat': PhosphorIconsFill.shareFat,
    'share-network': PhosphorIconsFill.shareNetwork,
    'sort-ascending': PhosphorIconsFill.sortAscending,
    'sort-descending': PhosphorIconsFill.sortDescending,
    'trash': PhosphorIconsFill.trash,
    'trash-simple': PhosphorIconsFill.trashSimple,
    'upload': PhosphorIconsFill.upload,
    'upload-simple': PhosphorIconsFill.uploadSimple,
    'x': PhosphorIconsFill.x,
    'x-circle': PhosphorIconsFill.xCircle,
    'x-square': PhosphorIconsFill.xSquare,

    // ─── Security & Authentication ───
    'fingerprint': PhosphorIconsFill.fingerprint,
    'fingerprint-simple': PhosphorIconsFill.fingerprintSimple,
    'key': PhosphorIconsFill.key,
    'lock': PhosphorIconsFill.lock,
    'lock-key': PhosphorIconsFill.lockKey,
    'lock-key-open': PhosphorIconsFill.lockKeyOpen,
    'lock-open': PhosphorIconsFill.lockOpen,
    'lock-simple': PhosphorIconsFill.lockSimple,
    'lock-simple-open': PhosphorIconsFill.lockSimpleOpen,
    'scan': PhosphorIconsFill.scan,
    'shield': PhosphorIconsFill.shield,
    'shield-check': PhosphorIconsFill.shieldCheck,
    'shield-star': PhosphorIconsFill.shieldStar,
    'shield-warning': PhosphorIconsFill.shieldWarning,

    // ─── Settings & Profile ───
    'gear': PhosphorIconsFill.gear,
    'gear-fine': PhosphorIconsFill.gearFine,
    'gear-six': PhosphorIconsFill.gearSix,
    'identification-badge': PhosphorIconsFill.identificationBadge,
    'identification-card': PhosphorIconsFill.identificationCard,
    'palette': PhosphorIconsFill.palette,
    'sliders': PhosphorIconsFill.sliders,
    'sliders-horizontal': PhosphorIconsFill.slidersHorizontal,
    'translate': PhosphorIconsFill.translate,
    'user': PhosphorIconsFill.user,
    'user-check': PhosphorIconsFill.userCheck,
    'user-circle': PhosphorIconsFill.userCircle,
    'user-circle-gear': PhosphorIconsFill.userCircleGear,
    'user-focus': PhosphorIconsFill.userFocus,
    'user-gear': PhosphorIconsFill.userGear,
    'user-list': PhosphorIconsFill.userList,
    'user-minus': PhosphorIconsFill.userMinus,
    'user-plus': PhosphorIconsFill.userPlus,
    'user-switch': PhosphorIconsFill.userSwitch,
    'users': PhosphorIconsFill.users,
    'users-three': PhosphorIconsFill.usersThree,
    'users-four': PhosphorIconsFill.usersFour,

    // ─── Notifications & Communication ───
    'bell': PhosphorIconsFill.bell,
    'bell-ringing': PhosphorIconsFill.bellRinging,
    'bell-simple': PhosphorIconsFill.bellSimple,
    'bell-simple-ringing': PhosphorIconsFill.bellSimpleRinging,
    'bell-simple-slash': PhosphorIconsFill.bellSimpleSlash,
    'bell-slash': PhosphorIconsFill.bellSlash,
    'envelope': PhosphorIconsFill.envelope,
    'envelope-simple': PhosphorIconsFill.envelopeSimple,
    'notification': PhosphorIconsFill.notification,

    // ─── Date & Time ───
    'calendar': PhosphorIconsFill.calendar,
    'calendar-blank': PhosphorIconsFill.calendarBlank,
    'calendar-check': PhosphorIconsFill.calendarCheck,
    'calendar-dot': PhosphorIconsFill.calendarDot,
    'calendar-dots': PhosphorIconsFill.calendarDots,
    'calendar-heart': PhosphorIconsFill.calendarHeart,
    'calendar-minus': PhosphorIconsFill.calendarMinus,
    'calendar-plus': PhosphorIconsFill.calendarPlus,
    'calendar-x': PhosphorIconsFill.calendarX,
    'clock': PhosphorIconsFill.clock,
    'clock-afternoon': PhosphorIconsFill.clockAfternoon,
    'clock-clockwise': PhosphorIconsFill.clockClockwise,
    'clock-counter-clockwise': PhosphorIconsFill.clockCounterClockwise,
    'hourglass': PhosphorIconsFill.hourglass,
    'hourglass-high': PhosphorIconsFill.hourglassHigh,
    'hourglass-low': PhosphorIconsFill.hourglassLow,
    'hourglass-medium': PhosphorIconsFill.hourglassMedium,
    'hourglass-simple': PhosphorIconsFill.hourglassSimple,
    'timer': PhosphorIconsFill.timer,

    // ─── UI & Layout ───
    'bookmark': PhosphorIconsFill.bookmark,
    'bookmark-simple': PhosphorIconsFill.bookmarkSimple,
    'bookmarks': PhosphorIconsFill.bookmarks,
    'bookmarks-simple': PhosphorIconsFill.bookmarksSimple,
    'circle': PhosphorIconsFill.circle,
    'circle-dashed': PhosphorIconsFill.circleDashed,
    'circle-half': PhosphorIconsFill.circleHalf,
    'columns': PhosphorIconsFill.columns,
    'crown': PhosphorIconsFill.crown,
    'crown-simple': PhosphorIconsFill.crownSimple,
    'diamond': PhosphorIconsFill.diamond,
    'dots-nine': PhosphorIconsFill.dotsNine,
    'dots-six': PhosphorIconsFill.dotsSix,
    'dots-six-vertical': PhosphorIconsFill.dotsSixVertical,
    'dots-three': PhosphorIconsFill.dotsThree,
    'dots-three-circle': PhosphorIconsFill.dotsThreeCircle,
    'dots-three-circle-vertical': PhosphorIconsFill.dotsThreeCircleVertical,
    'dots-three-outline': PhosphorIconsFill.dotsThreeOutline,
    'dots-three-outline-vertical': PhosphorIconsFill.dotsThreeOutlineVertical,
    'dots-three-vertical': PhosphorIconsFill.dotsThreeVertical,
    'flag': PhosphorIconsFill.flag,
    'flag-banner': PhosphorIconsFill.flagBanner,
    'grid-four': PhosphorIconsFill.gridFour,
    'grid-nine': PhosphorIconsFill.gridNine,
    'heart-straight': PhosphorIconsFill.heartStraight,
    'house': PhosphorIconsFill.house,
    'house-line': PhosphorIconsFill.houseLine,
    'house-simple': PhosphorIconsFill.houseSimple,
    'info': PhosphorIconsFill.info,
    'layout': PhosphorIconsFill.layout,
    'lightbulb': PhosphorIconsFill.lightbulb,
    'lightbulb-filament': PhosphorIconsFill.lightbulbFilament,
    'list': PhosphorIconsFill.list,
    'list-bullets': PhosphorIconsFill.listBullets,
    'list-checks': PhosphorIconsFill.listChecks,
    'list-dashes': PhosphorIconsFill.listDashes,
    'list-numbers': PhosphorIconsFill.listNumbers,
    'list-plus': PhosphorIconsFill.listPlus,
    'moon': PhosphorIconsFill.moon,
    'question': PhosphorIconsFill.question,
    'question-mark': PhosphorIconsFill.questionMark,
    'rows': PhosphorIconsFill.rows,
    'sparkle': PhosphorIconsFill.sparkle,
    'square': PhosphorIconsFill.square,
    'star': PhosphorIconsFill.star,
    'star-four': PhosphorIconsFill.starFour,
    'star-half': PhosphorIconsFill.starHalf,
    'sun': PhosphorIconsFill.sun,
    'tag': PhosphorIconsFill.tag,
    'tag-simple': PhosphorIconsFill.tagSimple,
    'target': PhosphorIconsFill.target,
    'toggle-left': PhosphorIconsFill.toggleLeft,
    'toggle-right': PhosphorIconsFill.toggleRight,
    'trophy': PhosphorIconsFill.trophy,
    'warning': PhosphorIconsFill.warning,
    'warning-circle': PhosphorIconsFill.warningCircle,
    'warning-diamond': PhosphorIconsFill.warningDiamond,
    'warning-octagon': PhosphorIconsFill.warningOctagon,

    // ─── Transaction Categories: Food & Dining ───
    'bowl-food': PhosphorIconsFill.bowlFood,
    'bowl-steam': PhosphorIconsFill.bowlSteam,
    'bread': PhosphorIconsFill.bread,
    'cake': PhosphorIconsFill.cake,
    'carrot': PhosphorIconsFill.carrot,
    'cheese': PhosphorIconsFill.cheese,
    'coffee': PhosphorIconsFill.coffee,
    'cooking-pot': PhosphorIconsFill.cookingPot,
    'egg': PhosphorIconsFill.egg,
    'fork-knife': PhosphorIconsFill.forkKnife,
    'hamburger': PhosphorIconsFill.hamburger,
    'ice-cream': PhosphorIconsFill.iceCream,
    'pizza': PhosphorIconsFill.pizza,
    'popcorn': PhosphorIconsFill.popcorn,
    'wine': PhosphorIconsFill.wine,
    'beer-stein': PhosphorIconsFill.beerStein,
    'coffee-bean': PhosphorIconsFill.coffeeBean,

    // ─── Transaction Categories: Transport & Travel ───
    'airplane': PhosphorIconsFill.airplane,
    'airplane-in-flight': PhosphorIconsFill.airplaneInFlight,
    'airplane-tilt': PhosphorIconsFill.airplaneTilt,
    'bicycle': PhosphorIconsFill.bicycle,
    'bus': PhosphorIconsFill.bus,
    'car': PhosphorIconsFill.car,
    'car-profile': PhosphorIconsFill.carProfile,
    'car-simple': PhosphorIconsFill.carSimple,
    'charging-station': PhosphorIconsFill.chargingStation,
    'compass': PhosphorIconsFill.compass,
    'gas-pump': PhosphorIconsFill.gasPump,
    'globe': PhosphorIconsFill.globe,
    'globe-simple': PhosphorIconsFill.globeSimple,
    'map-pin': PhosphorIconsFill.mapPin,
    'map-pin-line': PhosphorIconsFill.mapPinLine,
    'map-trifold': PhosphorIconsFill.mapTrifold,
    'motorcycle': PhosphorIconsFill.motorcycle,
    'navigation-arrow': PhosphorIconsFill.navigationArrow,
    'sailboat': PhosphorIconsFill.sailboat,
    'scooter': PhosphorIconsFill.scooter,
    'steering-wheel': PhosphorIconsFill.steeringWheel,
    'subway': PhosphorIconsFill.subway,
    'suitcase': PhosphorIconsFill.suitcase,
    'suitcase-rolling': PhosphorIconsFill.suitcaseRolling,
    'suitcase-simple': PhosphorIconsFill.suitcaseSimple,
    'taxi': PhosphorIconsFill.taxi,
    'train': PhosphorIconsFill.train,
    'train-simple': PhosphorIconsFill.trainSimple,
    'tram': PhosphorIconsFill.tram,
    'truck': PhosphorIconsFill.truck,
    'van': PhosphorIconsFill.van,

    // ─── Transaction Categories: Bills & Utilities ───
    'drop': PhosphorIconsFill.drop,
    'drop-half': PhosphorIconsFill.dropHalf,
    'drop-simple': PhosphorIconsFill.dropSimple,
    'lightning': PhosphorIconsFill.lightning,
    'lightning-a': PhosphorIconsFill.lightningA,
    'lightning-slash': PhosphorIconsFill.lightningSlash,
    'phone': PhosphorIconsFill.phone,
    'phone-call': PhosphorIconsFill.phoneCall,
    'newspaper': PhosphorIconsFill.newspaper,
    'television': PhosphorIconsFill.television,
    'television-simple': PhosphorIconsFill.televisionSimple,
    'wifi-high': PhosphorIconsFill.wifiHigh,
    'wifi-medium': PhosphorIconsFill.wifiMedium,
    'wifi-low': PhosphorIconsFill.wifiLow,
    'wifi-none': PhosphorIconsFill.wifiNone,
    'cell-signal-full': PhosphorIconsFill.cellSignalFull,
    'cell-signal-high': PhosphorIconsFill.cellSignalHigh,
    'cell-signal-medium': PhosphorIconsFill.cellSignalMedium,
    'cell-signal-low': PhosphorIconsFill.cellSignalLow,
    'cell-signal-none': PhosphorIconsFill.cellSignalNone,

    // ─── Transaction Categories: Entertainment ───
    'confetti': PhosphorIconsFill.confetti,
    'film-slate': PhosphorIconsFill.filmSlate,
    'film-strip': PhosphorIconsFill.filmStrip,
    'game-controller': PhosphorIconsFill.gameController,
    'guitar': PhosphorIconsFill.guitar,
    'headphones': PhosphorIconsFill.headphones,
    'headset': PhosphorIconsFill.headset,
    'microphone': PhosphorIconsFill.microphone,
    'music-note': PhosphorIconsFill.musicNote,
    'music-note-simple': PhosphorIconsFill.musicNoteSimple,
    'music-notes': PhosphorIconsFill.musicNotes,
    'ticket': PhosphorIconsFill.ticket,

    // ─── Transaction Categories: Health & Medical ───
    'first-aid': PhosphorIconsFill.firstAid,
    'first-aid-kit': PhosphorIconsFill.firstAidKit,
    'heart': PhosphorIconsFill.heart,
    'heartbeat': PhosphorIconsFill.heartbeat,
    'hospital': PhosphorIconsFill.hospital,
    'pill': PhosphorIconsFill.pill,
    'pulse': PhosphorIconsFill.pulse,
    'stethoscope': PhosphorIconsFill.stethoscope,
    'syringe': PhosphorIconsFill.syringe,
    'thermometer': PhosphorIconsFill.thermometer,
    'thermometer-simple': PhosphorIconsFill.thermometerSimple,

    // ─── Transaction Categories: Shopping & Retail ───
    'bag': PhosphorIconsFill.bag,
    'bag-simple': PhosphorIconsFill.bagSimple,
    'gift': PhosphorIconsFill.gift,
    'handbag': PhosphorIconsFill.handbag,
    'handbag-simple': PhosphorIconsFill.handbagSimple,

    // ─── Transaction Categories: Housing & Home ───
    'building': PhosphorIconsFill.building,
    'building-apartment': PhosphorIconsFill.buildingApartment,
    'building-office': PhosphorIconsFill.buildingOffice,
    'buildings': PhosphorIconsFill.buildings,
    'garage': PhosphorIconsFill.garage,
    'lamp': PhosphorIconsFill.lamp,
    'toolbox': PhosphorIconsFill.toolbox,
    'wrench': PhosphorIconsFill.wrench,

    // ─── Transaction Categories: Clothing & Fashion ───
    'boot': PhosphorIconsFill.boot,
    'dress': PhosphorIconsFill.dress,
    'high-heel': PhosphorIconsFill.highHeel,
    'hoodie': PhosphorIconsFill.hoodie,
    'sneaker': PhosphorIconsFill.sneaker,
    't-shirt': PhosphorIconsFill.tShirt,

    // ─── Transaction Categories: Education ───
    'book': PhosphorIconsFill.book,
    'book-open': PhosphorIconsFill.bookOpen,
    'book-open-text': PhosphorIconsFill.bookOpenText,
    'books': PhosphorIconsFill.books,
    'graduation-cap': PhosphorIconsFill.graduationCap,
    'student': PhosphorIconsFill.student,

    // ─── Transaction Categories: Family & Pets ───
    'baby': PhosphorIconsFill.baby,
    'baby-carriage': PhosphorIconsFill.babyCarriage,
    'bird': PhosphorIconsFill.bird,
    'cat': PhosphorIconsFill.cat,
    'dog': PhosphorIconsFill.dog,
    'paw-print': PhosphorIconsFill.pawPrint,

    // ─── Transaction Categories: Salary & Business ───
    'briefcase': PhosphorIconsFill.briefcase,
    'briefcase-metal': PhosphorIconsFill.briefcaseMetal,

    // ─── Transaction Categories: Sports & Fitness ───
    'barbell': PhosphorIconsFill.barbell,
    'person-simple-bike': PhosphorIconsFill.personSimpleBike,
    'person-simple-run': PhosphorIconsFill.personSimpleRun,
    'person-simple-walk': PhosphorIconsFill.personSimpleWalk,

    // ─── Transaction Categories: Nature ───
    'flower': PhosphorIconsFill.flower,
    'flower-lotus': PhosphorIconsFill.flowerLotus,
    'flower-tulip': PhosphorIconsFill.flowerTulip,
    'leaf': PhosphorIconsFill.leaf,
    'plant': PhosphorIconsFill.plant,
    'tree': PhosphorIconsFill.tree,

    // ─── Files & Data ───
    'file': PhosphorIconsFill.file,
    'file-audio': PhosphorIconsFill.fileAudio,
    'file-csv': PhosphorIconsFill.fileCsv,
    'file-dashed': PhosphorIconsFill.fileDashed,
    'file-doc': PhosphorIconsFill.fileDoc,
    'file-image': PhosphorIconsFill.fileImage,
    'file-minus': PhosphorIconsFill.fileMinus,
    'file-pdf': PhosphorIconsFill.filePdf,
    'file-plus': PhosphorIconsFill.filePlus,
    'file-sql': PhosphorIconsFill.fileSql,
    'file-text': PhosphorIconsFill.fileText,
    'file-xls': PhosphorIconsFill.fileXls,
    'files': PhosphorIconsFill.files,
    'folder': PhosphorIconsFill.folder,
    'folder-minus': PhosphorIconsFill.folderMinus,
    'folder-open': PhosphorIconsFill.folderOpen,
    'folder-plus': PhosphorIconsFill.folderPlus,
    'folder-simple': PhosphorIconsFill.folderSimple,
    'folder-user': PhosphorIconsFill.folderUser,
    'folders': PhosphorIconsFill.folders,

    // ─── Devices ───
    'desktop': PhosphorIconsFill.desktop,
    'device-mobile': PhosphorIconsFill.deviceMobile,
    'device-tablet': PhosphorIconsFill.deviceTablet,
    'devices': PhosphorIconsFill.devices,
    'laptop': PhosphorIconsFill.laptop,
    'monitor': PhosphorIconsFill.monitor,

    // ─── Brands & Social ───
    'apple-logo': PhosphorIconsFill.appleLogo,
    'google-logo': PhosphorIconsFill.googleLogo,
    'google-play-logo': PhosphorIconsFill.googlePlayLogo,
    'paypal-logo': PhosphorIconsFill.paypalLogo,
    'stripe-logo': PhosphorIconsFill.stripeLogo,

    // ─── Cloud & Sync ───
    'cloud': PhosphorIconsFill.cloud,
    'cloud-arrow-down': PhosphorIconsFill.cloudArrowDown,
    'cloud-arrow-up': PhosphorIconsFill.cloudArrowUp,
    'cloud-check': PhosphorIconsFill.cloudCheck,
    'cloud-slash': PhosphorIconsFill.cloudSlash,

    // ─── Misc ───
    'camera': PhosphorIconsFill.camera,
    'database': PhosphorIconsFill.database,
    'handshake': PhosphorIconsFill.handshake,
    'image': PhosphorIconsFill.image,
    'images': PhosphorIconsFill.images,
    'image-square': PhosphorIconsFill.imageSquare,
    'printer': PhosphorIconsFill.printer,
    'radio-button': PhosphorIconsFill.radioButton,
    'ruler': PhosphorIconsFill.ruler,
    'scissors': PhosphorIconsFill.scissors,
  };
}
